//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package cl.gmo.pos.venta.web.wscl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArchiveCAFResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "archiveCAFResult"
})
@XmlRootElement(name = "ArchiveCAFResponse")
public class ArchiveCAFResponse {

    @XmlElement(name = "ArchiveCAFResult")
    protected String archiveCAFResult;

    /**
     * Gets the value of the archiveCAFResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveCAFResult() {
        return archiveCAFResult;
    }

    /**
     * Sets the value of the archiveCAFResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveCAFResult(String value) {
        this.archiveCAFResult = value;
    }

}
